/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   main.c                                             :+:    :+:            */
/*                                                     +:+                    */
/*   By: fbes <fbes@student.codam.nl>                 +#+                     */
/*                                                   +#+                      */
/*   Created: 2021/06/10 17:25:40 by fbes          #+#    #+#                 */
/*   Updated: 2021/11/01 21:33:41 by fbes          ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "libft.h"
#include "push_swap.h"

/**
 * Free the stacks and print error, then exits
 * @param *a	Stack A to free
 * @param *b	Stack B to free
 */
static void	exit_error(t_stack *a, t_stack *b)
{
	if (a)
		free_stack(a);
	if (b)
		free_stack(b);
	write(2, "Error\n", 6);
	exit(EXIT_FAILURE);
}

/**
 * Free the string array generated by ft_split and print error, then exits
 * @param *a	Stack A to free
 * @param *b	Stack B to free
 * @param **spl	The string array to free (generated by ft_split)
 */
static void	parse_space_sep_str_err(t_stack *a, t_stack *b, char **spl)
{
	ft_free_double_ptr((void **)spl);
	exit_error(a, b);
}

/**
 * Parse a string with numbers, divided by spaces
 * @param *a	The stack to push the numbers to
 * @param *b	Stack B to free in case of error
 * @param *s	The string with numbers to parse
 * @param *n	A pointer to the integer to parse to
 */
static void	parse_space_sep_str(t_stack *a, t_stack *b, char *s, int *n)
{
	char	**spl;
	int		i;

	if (only_spaces(s))
		return ;
	spl = ft_split(s, ' ');
	if (!spl)
		exit_error(a, b);
	i = 0;
	while (spl[i])
		i++;
	if (i == 0)
		parse_space_sep_str_err(a, b, spl);
	while (i > 0)
	{
		if (parse_num(a, n, spl[i - 1]) > 0)
		{
			if (!push(a, NULL, *n))
				parse_space_sep_str_err(a, b, spl);
		}
		else
			parse_space_sep_str_err(a, b, spl);
		i--;
	}
	ft_free_double_ptr((void **)spl);
}

/**
 * Parse the argv arguments given to the program
 * @param *a		The stack to parse the numbers to
 * @param *b		Stack B, gets freed on error
 * @param argc		The amount of arguments in argv
 * @param **argv	The arguments given to the program
 */
static void	handle_argv(t_stack *a, t_stack *b, int argc, char **argv)
{
	int		i;
	int		n;

	i = argc - 1;
	while (i > 0)
	{
		if (ft_strchr(argv[i], ' '))
			parse_space_sep_str(a, b, argv[i], &n);
		else if (ft_strlen(argv[i]) > 0)
		{
			if (parse_num(a, &n, argv[i]) > 0)
			{
				if (!push(a, NULL, n))
					exit_error(a, b);
			}
			else
				exit_error(a, b);
		}
		i--;
	}
}

int	main(int argc, char **argv)
{
	t_stack		*a;
	t_stack		*b;

	if (argc < 2)
		return (EXIT_SUCCESS);
	a = new_stack('a');
	b = new_stack('b');
	if (a && b)
	{
		handle_argv(a, b, argc, argv);
		sort(a, b);
	}
	free_stack(a);
	free_stack(b);
	exit(EXIT_SUCCESS);
}
